// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRZ1H52FIDMIMnQLzo7_3y9KaP4lCN1k',
    appId: '1:1003736937002:web:ed4c529b82e52ffad00953',
    messagingSenderId: '1003736937002',
    projectId: 'unistay-afca2',
    authDomain: 'unistay-afca2.firebaseapp.com',
    storageBucket: 'unistay-afca2.appspot.com',
    measurementId: 'G-GBWV0C56N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQ-VYW-hDnx3RsSA7Rgcry1Oq-UFSdVY',
    appId: '1:1003736937002:android:8bdccadf47d159a8d00953',
    messagingSenderId: '1003736937002',
    projectId: 'unistay-afca2',
    storageBucket: 'unistay-afca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9iySG8NJoG2UE3d1w-1KcIrx92T1q2Vs',
    appId: '1:1003736937002:ios:d23729070eecf903d00953',
    messagingSenderId: '1003736937002',
    projectId: 'unistay-afca2',
    storageBucket: 'unistay-afca2.appspot.com',
    iosBundleId: 'com.example.uniStay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9iySG8NJoG2UE3d1w-1KcIrx92T1q2Vs',
    appId: '1:1003736937002:ios:2ee4b3319058ab1cd00953',
    messagingSenderId: '1003736937002',
    projectId: 'unistay-afca2',
    storageBucket: 'unistay-afca2.appspot.com',
    iosBundleId: 'com.example.uniStay.RunnerTests',
  );
}
